"""Bundle the logo and fonts into embedded.js as data URIs.

The page loads everything from embedded.js so it works both when hosted and
when index.html is opened straight from disk (browsers block canvas export
for images and fonts loaded from file:// URLs).

Run after changing anything in assets/ or fonts/:  python3 build-embedded.py
"""
import base64
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
FILES = {
    "logoText": ("assets/stake-logo-text.png", "image/png"),
    "fontRegular": ("fonts/selawik-regular.woff", "font/woff"),
    "fontBold": ("fonts/selawik-bold.woff", "font/woff"),
}

out = {}
for key, (path, mime) in FILES.items():
    with open(os.path.join(HERE, path), "rb") as f:
        out[key] = f"data:{mime};base64," + base64.b64encode(f.read()).decode()

with open(os.path.join(HERE, "embedded.js"), "w") as f:
    f.write("// Generated by build-embedded.py. Do not edit by hand.\n")
    f.write("window.EMBEDDED = " + json.dumps(out, indent=0) + ";\n")
print("wrote embedded.js")
